language: ruby
cache: bundler
sudo: false
env: TEST=true

rvm:
  - 2.0.0
  - 2.1
  - 2.2.5
  - 2.3.1
  - ruby-head

gemfile:
  - Gemfile

script: "bundle exec rake test"

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
